### ISSUE TITLE
Capture to note

### ISSUE THREAD

**Issue by eidorb** [anglinb/foam-capture#1]
https://github.com/anglinb/foam-capture/blob/b5527d430e98186a24ad2ab6ec1468597c894d93/src/utils/capture-to-inbox.ts#L10

Can `captureToInbox` be generalised to a ` captureToNote` function, that would allow specifying `relativePath`?

This option could then be exposed in `anglinb/foam-capture-action`. Of course, `index.md` could remain a default.

**Comment by anglinb** [comment]
👋 @eidorb, ya could definitely do that! Not sure when I'll have time to do that but if you're up for it would be happy to review and get a PR merged in!
